/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import CodeBehind.ImgModifier;
import CodeBehind.Logs.AfficherLogDialog;
import CodeBehind.Logs.FichierLog;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Eliott
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    private boolean _isLogDialogOpened = false;
    private FichierLog _fLog;
    private AfficherLogDialog _ald;
    private BufferedImage _imgBefore;
    private BufferedImage _imgAfter;
    private ImgModifier _iMod;
    
    public MainWindow() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        _fLog = new FichierLog();
        _iMod = new ImgModifier();
        BufferedImage img = null; 
        File f = null; 
  
        //read image 
        try
        { 
            f = new File("C:\\Users\\Eliott\\Desktop\\test.jpg"); 
            img = ImageIO.read(f); 
        } 
        catch(IOException e) 
        { 
            System.out.println(e); 
        } 
        _fLog.addLog("Reading Image");
        
        
        BufferedImage temp = new BufferedImage(img.getWidth(), 
                    img.getHeight(), BufferedImage.TYPE_INT_RGB); 
  
        BufferedImage temp2 = new BufferedImage(256, 256, BufferedImage.TYPE_INT_RGB);
        
        Graphics graphics = temp.getGraphics(); 
        graphics.drawImage(img, 0, 0, null);

        graphics.drawImage(temp, 0, 0, 256, 256, 0, 0, img.getWidth(), img.getHeight(), null);
        graphics.dispose();
        
        temp2 = temp.getSubimage(0, 0 , 256, 256);
        setImgBefore(temp2);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAfter = new javax.swing.JLabel();
        jLabelBefore = new javax.swing.JLabel();
        jBtnAfter2Before = new javax.swing.JButton();
        jBtnGreyscale = new javax.swing.JButton();
        jBtnNeg = new javax.swing.JButton();
        jSliderTreshold = new javax.swing.JSlider();
        jBtnTreshold = new javax.swing.JToggleButton();
        javax.swing.JButton jBtnMedianFilter = new javax.swing.JButton();
        jBtnZoom = new javax.swing.JButton();
        jBtnMediumFilter = new javax.swing.JButton();
        jBtnGaussianFilter = new javax.swing.JButton();
        jBtnLaplacianFilter = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAffLog = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelAfter.setPreferredSize(new java.awt.Dimension(256, 256));

        jLabelBefore.setText("jLabel1");
        jLabelBefore.setPreferredSize(new java.awt.Dimension(256, 256));

        jBtnAfter2Before.setText("<=>");
        jBtnAfter2Before.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAfter2BeforeActionPerformed(evt);
            }
        });

        jBtnGreyscale.setText("Greyscale");
        jBtnGreyscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGreyscaleActionPerformed(evt);
            }
        });

        jBtnNeg.setText("Negative");
        jBtnNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNegActionPerformed(evt);
            }
        });

        jSliderTreshold.setMaximum(255);
        jSliderTreshold.setMinorTickSpacing(1);
        jSliderTreshold.setPaintTicks(true);
        jSliderTreshold.setToolTipText("");
        jSliderTreshold.setValue(128);
        jSliderTreshold.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTresholdMouseDragged(evt);
            }
        });

        jBtnTreshold.setText("Treshold");
        jBtnTreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTresholdActionPerformed(evt);
            }
        });

        jBtnMedianFilter.setText("Median filter");
        jBtnMedianFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMedianFilterActionPerformed(evt);
            }
        });

        jBtnZoom.setText("+");
        jBtnZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZoomActionPerformed(evt);
            }
        });

        jBtnMediumFilter.setText("Medium filter");
        jBtnMediumFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMediumFilterActionPerformed(evt);
            }
        });

        jBtnGaussianFilter.setText("Gaussian filter");
        jBtnGaussianFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGaussianFilterActionPerformed(evt);
            }
        });

        jBtnLaplacianFilter.setText("Laplacian of Gaussian filter");
        jBtnLaplacianFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLaplacianFilterActionPerformed(evt);
            }
        });

        jMenuAffLog.setText("Option");
        jMenuAffLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAffLogActionPerformed(evt);
            }
        });

        jCheckBoxMenuItem1.setText("Afficher le log");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAffLog.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenuAffLog);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jBtnAfter2Before)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAfter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnZoom)
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnMediumFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(jBtnMedianFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnGreyscale)
                                    .addComponent(jBtnNeg))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSliderTreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jBtnTreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jBtnLaplacianFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jBtnGaussianFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAfter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAfter2Before))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtnGreyscale)
                                .addComponent(jBtnMedianFilter))
                            .addComponent(jBtnTreshold, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtnNeg)
                                .addComponent(jBtnMediumFilter))
                            .addComponent(jSliderTreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jBtnZoom)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGaussianFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnLaplacianFilter)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new FichierLog().addLog("--FIN DE LA SESSION");
        new FichierLog().addLog("");
        new FichierLog().addLog("");
    }//GEN-LAST:event_formWindowClosing

    private void jMenuAffLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAffLogActionPerformed

    }//GEN-LAST:event_jMenuAffLogActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        if(_isLogDialogOpened == false)
        {
            _isLogDialogOpened = true;
            _ald = new AfficherLogDialog(this, false);
            _ald.setVisible(true);
        }
        else
        {
            _ald.dispose();
            _isLogDialogOpened = false;
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jBtnAfter2BeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAfter2BeforeActionPerformed
        
        try {
            _fLog.addLog("Swapping before and after");
            BufferedImage tmp = _iMod.copyImage(_imgAfter);
            _imgAfter = _imgBefore;
            _imgBefore = tmp;
            setImgAfter(_imgAfter);
            setImgBefore(tmp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : No Result Image");
            _fLog.addLog("Can't swap : no after image");
        }

        
    }//GEN-LAST:event_jBtnAfter2BeforeActionPerformed

    private void jBtnGreyscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGreyscaleActionPerformed
        // TODO add your handling code here:
        setImgAfter(_iMod.ToGreyscale(_imgBefore));
        _fLog.addLog("Image to greyscale");
    }//GEN-LAST:event_jBtnGreyscaleActionPerformed

    private void jBtnNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNegActionPerformed
        setImgAfter(_iMod.Negative(_imgBefore));
        _fLog.addLog("Image to greyscale");
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnNegActionPerformed

    private void jSliderTresholdMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTresholdMouseDragged
        // TODO add your handling code here:
        if(jBtnTreshold.isSelected())
        {
            setImgAfter(_iMod.Treshold(_imgBefore, jSliderTreshold.getValue()));
            //_fLog.addLog("Treshold");
        }
        
    }//GEN-LAST:event_jSliderTresholdMouseDragged

    private void jBtnTresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTresholdActionPerformed
        // TODO add your handling code here:
        if(jBtnTreshold.isSelected())
        {
            setImgAfter(_iMod.Treshold(_imgBefore, jSliderTreshold.getValue()));
            //_fLog.addLog("Treshold");
        }
    }//GEN-LAST:event_jBtnTresholdActionPerformed

    private void jBtnMedianFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMedianFilterActionPerformed
        // TODO add your handling code here:
        setImgAfter(_iMod.FiltreMedian(_imgBefore));
        _fLog.addLog("Median Filter");
    }//GEN-LAST:event_jBtnMedianFilterActionPerformed

    private void jBtnZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZoomActionPerformed
        int zoomLevel = 2;
        int imageWidth = _imgBefore.getWidth();
        int imageHeight = _imgBefore.getHeight();
        int newImageWidth = imageWidth * zoomLevel;
        int newImageHeight = imageHeight * zoomLevel;
        BufferedImage resizedImage = new BufferedImage(newImageWidth , newImageHeight, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = resizedImage.createGraphics();
        g.drawImage(_imgBefore, 0, 0, newImageWidth , newImageHeight , null);
        g.dispose();
        setImgBefore(resizedImage);
    }//GEN-LAST:event_jBtnZoomActionPerformed

    private void jBtnMediumFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMediumFilterActionPerformed
        // TODO add your handling code here:
        setImgAfter(_iMod.FiltreMoyen(_imgBefore));
        _fLog.addLog("Medium Filter");
    }//GEN-LAST:event_jBtnMediumFilterActionPerformed

    private void jBtnGaussianFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGaussianFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGaussianFilterActionPerformed

    private void jBtnLaplacianFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLaplacianFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnLaplacianFilterActionPerformed

    private void setImgAfter(BufferedImage img)
    {
        _imgAfter = img;
        jLabelAfter.setIcon(new ImageIcon(_imgAfter));
        _fLog.addLog("Image after changed");
    }
    
    private void setImgBefore(BufferedImage img)
    {
        _imgBefore = img;
        jLabelBefore.setIcon(new ImageIcon(_imgBefore));
        _fLog.addLog("Image before changed");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAfter2Before;
    private javax.swing.JButton jBtnGaussianFilter;
    private javax.swing.JButton jBtnGreyscale;
    private javax.swing.JButton jBtnLaplacianFilter;
    private javax.swing.JButton jBtnMediumFilter;
    private javax.swing.JButton jBtnNeg;
    private javax.swing.JToggleButton jBtnTreshold;
    private javax.swing.JButton jBtnZoom;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabelAfter;
    private javax.swing.JLabel jLabelBefore;
    private javax.swing.JMenu jMenuAffLog;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSlider jSliderTreshold;
    // End of variables declaration//GEN-END:variables
}
