/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import CodeBehind.ImgModifier;
import CodeBehind.Logs.AfficherLogDialog;
import CodeBehind.Logs.FichierLog;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.Graphics2D;
import java.awt.TrayIcon;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.FileChooserUI;
import jdk.jshell.spi.ExecutionControl;

/**
 *
 * @author Eliott
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    private boolean _isLogDialogOpened = false;
    private FichierLog _fLog;
    private AfficherLogDialog _ald;
    private BufferedImage _imgBefore;
    private BufferedImage _imgAfter;
    private ImgModifier _iMod;
    private int x1, y1, x2, y2;
    private int minValue, maxValue;
    
    public MainWindow() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        _fLog = new FichierLog();
        _iMod = new ImgModifier();
        BufferedImage img = null; 
        File f = null; 
  
         
        try
        { 
            f = new File("C:\\Users\\Eliott\\Desktop\\xxxx.jpg"); 
            img = ImageIO.read(f); 
        } 
        catch(IOException e) 
        { 
            JOptionPane.showMessageDialog(this, "Fail to open the file", "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
        } 
        _fLog.addLog("Reading Image");
        
        
        BufferedImage temp = new BufferedImage(img.getWidth(), 
                    img.getHeight(), BufferedImage.TYPE_INT_RGB); 
  
        BufferedImage temp2 = new BufferedImage(256, 256, BufferedImage.TYPE_INT_RGB);
        
        Graphics graphics = temp.getGraphics(); 
        graphics.drawImage(img, 0, 0, null);

        graphics.drawImage(temp, 0, 0, 256, 256, 0, 0, img.getWidth(), img.getHeight(), null);
        graphics.dispose();
        
        temp2 = temp.getSubimage(0, 0 , 256, 256);
        setImgBefore(temp2);
        

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnAfter2Before = new javax.swing.JButton();
        jBtnGreyscale = new javax.swing.JButton();
        jBtnNeg = new javax.swing.JButton();
        jSliderTreshold = new javax.swing.JSlider();
        jBtnTreshold = new javax.swing.JToggleButton();
        jBtnZoom1 = new javax.swing.JButton();
        jBtnMultiTreshold = new javax.swing.JButton();
        jBtnPalette = new javax.swing.JButton();
        jTextFieldZoom2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabelAfter = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelBefore = new javax.swing.JLabel();
        jBtnZoom2 = new javax.swing.JButton();
        jTextFieldZoom1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLblHistoBefore = new javax.swing.JLabel();
        jLblHV = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLblHistoAfter = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAffLog = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuFilltres = new javax.swing.JMenu();
        jMenuItemMediumF = new javax.swing.JMenuItem();
        jMenuItemMedian = new javax.swing.JMenuItem();
        jMenuItemBelgianFilter = new javax.swing.JMenuItem();
        jMenuItemLaplacian = new javax.swing.JMenuItem();
        jMenuItemKirsh = new javax.swing.JMenuItem();
        jMenuItemSobel = new javax.swing.JMenuItem();
        jMenuItemPrewitt = new javax.swing.JMenuItem();
        jMenuItemRoberts = new javax.swing.JMenuItem();
        jMenuMorphologie = new javax.swing.JMenu();
        jMenuItemOuverture = new javax.swing.JMenuItem();
        jMenuItemFermeture = new javax.swing.JMenuItem();
        jMenuItemErosion = new javax.swing.JMenuItem();
        jMenuItemDilatation = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image processing");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jBtnAfter2Before.setText("<=");
        jBtnAfter2Before.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAfter2BeforeActionPerformed(evt);
            }
        });

        jBtnGreyscale.setText("Greyscale");
        jBtnGreyscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGreyscaleActionPerformed(evt);
            }
        });

        jBtnNeg.setText("Negative");
        jBtnNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNegActionPerformed(evt);
            }
        });

        jSliderTreshold.setMaximum(255);
        jSliderTreshold.setMinorTickSpacing(1);
        jSliderTreshold.setPaintTicks(true);
        jSliderTreshold.setToolTipText("");
        jSliderTreshold.setValue(128);
        jSliderTreshold.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTresholdMouseDragged(evt);
            }
        });

        jBtnTreshold.setText("Treshold");
        jBtnTreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTresholdActionPerformed(evt);
            }
        });

        jBtnZoom1.setText("+");
        jBtnZoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZoom1ActionPerformed(evt);
            }
        });

        jBtnMultiTreshold.setText("Multi-Treshold");
        jBtnMultiTreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiTresholdActionPerformed(evt);
            }
        });

        jBtnPalette.setText("Palette");
        jBtnPalette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPaletteActionPerformed(evt);
            }
        });

        jTextFieldZoom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZoom2ActionPerformed(evt);
            }
        });

        jScrollPane2.setPreferredSize(new java.awt.Dimension(256, 256));

        jLabelAfter.setPreferredSize(null);
        jScrollPane2.setViewportView(jLabelAfter);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(256, 256));

        jLabelBefore.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLabelBefore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBeforeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelBeforeMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jLabelBefore);

        jBtnZoom2.setText("+");
        jBtnZoom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZoom2ActionPerformed(evt);
            }
        });

        jTextFieldZoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZoom1ActionPerformed(evt);
            }
        });

        jButton1.setText("Expansion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLblHistoBefore.setBackground(new java.awt.Color(255, 0, 0));
        jLblHistoBefore.setForeground(new java.awt.Color(127, 127, 127));

        jLabel1.setText("255");

        jLabel2.setText("0");

        jLblHistoAfter.setBackground(new java.awt.Color(255, 0, 0));
        jLblHistoAfter.setForeground(new java.awt.Color(127, 127, 127));

        jLabel3.setText("255");

        jLabel4.setText("0");

        jMenuAffLog.setText("Option");
        jMenuAffLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAffLogActionPerformed(evt);
            }
        });

        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuAffLog.add(jMenuItemOpen);

        jCheckBoxMenuItem1.setText("Afficher le log");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAffLog.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenuAffLog);

        jMenuFilltres.setText("Filtres");

        jMenuItemMediumF.setText("Medium Filter");
        jMenuItemMediumF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMediumFActionPerformed(evt);
            }
        });
        jMenuFilltres.add(jMenuItemMediumF);

        jMenuItemMedian.setText("Median Filter");
        jMenuItemMedian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedianActionPerformed(evt);
            }
        });
        jMenuFilltres.add(jMenuItemMedian);

        jMenuItemBelgianFilter.setText("BelgianFilter");
        jMenuItemBelgianFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBelgianFilterActionPerformed(evt);
            }
        });
        jMenuFilltres.add(jMenuItemBelgianFilter);

        jMenuItemLaplacian.setText("Laplacian");
        jMenuItemLaplacian.setToolTipText("");
        jMenuItemLaplacian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLaplacianActionPerformed(evt);
            }
        });
        jMenuFilltres.add(jMenuItemLaplacian);

        jMenuItemKirsh.setText("Kirsh");
        jMenuItemKirsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKirshActionPerformed(evt);
            }
        });
        jMenuFilltres.add(jMenuItemKirsh);

        jMenuItemSobel.setText("Sobel");
        jMenuItemSobel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobelActionPerformed(evt);
            }
        });
        jMenuFilltres.add(jMenuItemSobel);

        jMenuItemPrewitt.setText("Prewitt");
        jMenuItemPrewitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrewittActionPerformed(evt);
            }
        });
        jMenuFilltres.add(jMenuItemPrewitt);

        jMenuItemRoberts.setText("Roberts");
        jMenuItemRoberts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRobertsActionPerformed(evt);
            }
        });
        jMenuFilltres.add(jMenuItemRoberts);

        jMenuBar1.add(jMenuFilltres);

        jMenuMorphologie.setText("Morphologie");

        jMenuItemOuverture.setText("Open");
        jMenuMorphologie.add(jMenuItemOuverture);

        jMenuItemFermeture.setText("Close");
        jMenuMorphologie.add(jMenuItemFermeture);

        jMenuItemErosion.setText("Erosion");
        jMenuMorphologie.add(jMenuItemErosion);

        jMenuItemDilatation.setText("Dilatation");
        jMenuMorphologie.add(jMenuItemDilatation);

        jMenuBar1.add(jMenuMorphologie);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLblHV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnGreyscale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnTreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jBtnMultiTreshold)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSliderTreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnPalette, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnZoom1)
                            .addComponent(jTextFieldZoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(241, 241, 241)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(327, 327, 327))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLblHistoBefore, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnAfter2Before)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLblHistoAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnZoom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldZoom2))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jBtnAfter2Before))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jBtnZoom1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldZoom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jBtnZoom2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldZoom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnGreyscale)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSliderTreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnPalette))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnTreshold)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnNeg))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jBtnMultiTreshold)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblHistoBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblHistoAfter, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addComponent(jLblHV)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new FichierLog().addLog("--FIN DE LA SESSION");
        new FichierLog().addLog("");
        new FichierLog().addLog("");
    }//GEN-LAST:event_formWindowClosing

    private void jMenuAffLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAffLogActionPerformed

    }//GEN-LAST:event_jMenuAffLogActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        if(_isLogDialogOpened == false)
        {
            _isLogDialogOpened = true;
            _ald = new AfficherLogDialog(this, false);
            _ald.setVisible(true);
        }
        else
        {
            _ald.dispose();
            _isLogDialogOpened = false;
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jBtnAfter2BeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAfter2BeforeActionPerformed
        
        try {
            _fLog.addLog("Swapping before and after");
            BufferedImage tmp = _iMod.copyImage(_imgAfter);
            //_imgAfter = _imgBefore;
            _imgBefore = tmp;
            //setImgAfter(_imgAfter);
            setImgBefore(tmp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : No Result Image");
            _fLog.addLog("Can't swap : no after image");
        }

        
    }//GEN-LAST:event_jBtnAfter2BeforeActionPerformed

    private void jBtnGreyscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGreyscaleActionPerformed
        // TODO add your handling code here:
        setImgAfter(_iMod.ToGreyscale(_imgBefore));
        _fLog.addLog("Image to greyscale");
    }//GEN-LAST:event_jBtnGreyscaleActionPerformed

    private void jBtnNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNegActionPerformed
        setImgAfter(_iMod.Negative(_imgBefore));
        _fLog.addLog("Image to greyscale");
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnNegActionPerformed

    private void jSliderTresholdMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTresholdMouseDragged
        // TODO add your handling code here:
        if(jBtnTreshold.isSelected())
        {
            setImgAfter(_iMod.Treshold(_imgBefore, jSliderTreshold.getValue()));
            //_fLog.addLog("Treshold");
        }
        
    }//GEN-LAST:event_jSliderTresholdMouseDragged

    private void jBtnTresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTresholdActionPerformed
        // TODO add your handling code here:
        if(jBtnTreshold.isSelected())
        {
            setImgAfter(_iMod.Treshold(_imgBefore, jSliderTreshold.getValue()));
            //_fLog.addLog("Treshold");
        }
    }//GEN-LAST:event_jBtnTresholdActionPerformed

    private void jBtnZoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZoom1ActionPerformed
        setImgBefore(_iMod.Zoom(_imgBefore, jTextFieldZoom1.getText()));
        _fLog.addLog("Zoom de coef " + jTextFieldZoom1.getText());
    }//GEN-LAST:event_jBtnZoom1ActionPerformed

    private void jBtnMultiTresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiTresholdActionPerformed
        // TODO add your handling code here:
        int[] tab = new int[9];
        MTresholdDialog mtd = new MTresholdDialog(this, true, tab);
        mtd.setVisible(true);
        System.out.println(tab[0]);
        System.out.println(tab[1]);
        System.out.println(tab[2]);
        System.out.println(tab[3]);
        System.out.println(tab[4]);
        System.out.println(tab[5]);
        System.out.println(tab[6]);
        System.out.println(tab[7]);
        System.out.println(tab[8]);
        setImgAfter(_iMod.MultiTreshold(_imgBefore, tab));
    }//GEN-LAST:event_jBtnMultiTresholdActionPerformed

    private void jBtnPaletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPaletteActionPerformed
        // TODO add your handling code here:
        PaletteDialog pd = new PaletteDialog(this, true);
        Thread tpd = new Thread(pd);
        tpd.start();
        pd.setVisible(true);
    }//GEN-LAST:event_jBtnPaletteActionPerformed

    private void jTextFieldZoom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZoom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZoom2ActionPerformed

    private void jBtnZoom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZoom2ActionPerformed
        // TODO add your handling code here:
        setImgAfter(_iMod.Zoom(_imgAfter, jTextFieldZoom2.getText()));
        _fLog.addLog("Zoom de coef " + jTextFieldZoom2.getText());
    }//GEN-LAST:event_jBtnZoom2ActionPerformed

    private void jTextFieldZoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZoom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZoom1ActionPerformed

    private void jLabelBeforeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBeforeMousePressed
        // TODO add your handling code here:
        x1 = evt.getX();
        y1 = evt.getY(); 
    }//GEN-LAST:event_jLabelBeforeMousePressed

    private void jLabelBeforeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBeforeMouseReleased
        // TODO add your handling code here:
        x2 = evt.getX();
        y2 = evt.getY(); 
        
        BufferedImage img = _iMod.copyImage(_imgBefore);
        
        Rectangle rect;
        if(x1 <= x2)
            if(y1 <= y2)
                rect = new Rectangle(x1, y1, x2-x1, y2-y1);
            else
                rect = new Rectangle(x1, y2, x2-x1, y1-y2);
        else
            if(y1 <= y2)
                rect = new Rectangle(x2, y1, x1-x2, y2-y1);
            else
                rect = new Rectangle(x2, y2, x1-x2, y1-y2);
        
        setImgAfter(img.getSubimage((int)(rect.x), (int)(rect.y), (int)(rect.width), (int)(rect.height)));
    }//GEN-LAST:event_jLabelBeforeMouseReleased

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        // TODO add your handling code here:
        BufferedImage  img;
        JFileChooser fd = new JFileChooser();
        fd.showOpenDialog(this);
        try
        { 
            _fLog.addLog(fd.getSelectedFile().getAbsolutePath());
            File f = new File(fd.getSelectedFile().getAbsolutePath()); 
            img = ImageIO.read(f); 
            setImgBefore(img);
        } 
        catch(IOException e) 
        { 
            JOptionPane.showMessageDialog(this, "Fail to open the file", "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
        } 
        
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setImgBefore(_iMod.scale(_imgBefore, 2, 2));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemKirshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKirshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemKirshActionPerformed

    private void jMenuItemSobelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSobelActionPerformed

    private void jMenuItemPrewittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrewittActionPerformed
        // TODO add your handling code here:
        setImgAfter(_iMod.FiltreDePrewitt(_imgBefore));
    }//GEN-LAST:event_jMenuItemPrewittActionPerformed

    private void jMenuItemRobertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRobertsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRobertsActionPerformed

    private void jMenuItemBelgianFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBelgianFilterActionPerformed
        // TODO add your handling code here:
        setImgAfter(_iMod.FiltreGaussien(_imgBefore, 0.3));
    }//GEN-LAST:event_jMenuItemBelgianFilterActionPerformed

    private void jMenuItemLaplacianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLaplacianActionPerformed
        // TODO add your handling code here:
        setImgAfter(_iMod.FiltreLaplacien(_imgBefore));
    }//GEN-LAST:event_jMenuItemLaplacianActionPerformed

    private void jMenuItemMedianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedianActionPerformed
        // TODO add your handling code here:
        setImgAfter(_iMod.FiltreMedian(_imgBefore));
        _fLog.addLog("Median Filter");
    }//GEN-LAST:event_jMenuItemMedianActionPerformed

    private void jMenuItemMediumFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMediumFActionPerformed
        // TODO add your handling code here:
        setImgAfter(_iMod.FiltreMoyen(_imgBefore));
        _fLog.addLog("Medium Filter");
    }//GEN-LAST:event_jMenuItemMediumFActionPerformed

    
    private void setImgAfter(BufferedImage img)
    {
        _imgAfter = img;
        jLabelAfter.setIcon(new ImageIcon(_imgAfter));
        jLblHistoAfter.setIcon(new ImageIcon(_iMod.Histogramme(_imgAfter, jLblHistoAfter.getWidth(), jLblHistoAfter.getHeight())));
        _fLog.addLog("Image after changed");
    }
    
    private void setImgBefore(BufferedImage img)
    {
        _imgBefore = img;
        jLabelBefore.setIcon(new ImageIcon(_imgBefore));
        jLblHistoBefore.setIcon(new ImageIcon(_iMod.Histogramme(_imgBefore, jLblHistoBefore.getWidth(), jLblHistoBefore.getHeight())));
        _fLog.addLog("Image before changed");
    }
    
    protected void setColor(Color c)
    {
        setImgAfter(_iMod.ColorChange(_imgBefore, c.getRGB()));
    }

    private void histogramEgalisation()
    {
        int dyn = maxValue-minValue;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAfter2Before;
    private javax.swing.JButton jBtnGreyscale;
    private javax.swing.JButton jBtnMultiTreshold;
    private javax.swing.JButton jBtnNeg;
    private javax.swing.JButton jBtnPalette;
    private javax.swing.JToggleButton jBtnTreshold;
    private javax.swing.JButton jBtnZoom1;
    private javax.swing.JButton jBtnZoom2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAfter;
    private javax.swing.JLabel jLabelBefore;
    private javax.swing.JLabel jLblHV;
    private javax.swing.JLabel jLblHistoAfter;
    private javax.swing.JLabel jLblHistoBefore;
    private javax.swing.JMenu jMenuAffLog;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFilltres;
    private javax.swing.JMenuItem jMenuItemBelgianFilter;
    private javax.swing.JMenuItem jMenuItemDilatation;
    private javax.swing.JMenuItem jMenuItemErosion;
    private javax.swing.JMenuItem jMenuItemFermeture;
    private javax.swing.JMenuItem jMenuItemKirsh;
    private javax.swing.JMenuItem jMenuItemLaplacian;
    private javax.swing.JMenuItem jMenuItemMedian;
    private javax.swing.JMenuItem jMenuItemMediumF;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemOuverture;
    private javax.swing.JMenuItem jMenuItemPrewitt;
    private javax.swing.JMenuItem jMenuItemRoberts;
    private javax.swing.JMenuItem jMenuItemSobel;
    private javax.swing.JMenu jMenuMorphologie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderTreshold;
    private javax.swing.JTextField jTextFieldZoom1;
    private javax.swing.JTextField jTextFieldZoom2;
    // End of variables declaration//GEN-END:variables

}
