/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import CodeBehind.ImgModifier;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;

/**
 *
 * @author Eliott
 */
public class MTresholdDialog extends javax.swing.JDialog {

    private int[] tab;
    /**
     * Creates new form MTresholdDialog
     */
    public MTresholdDialog(java.awt.Frame parent, boolean modal, int [] tabIn) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        tab = tabIn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderTreshold1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSliderTreshold2 = new javax.swing.JSlider();
        jLblFrom1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSliderTreshold3 = new javax.swing.JSlider();
        jLblBy1 = new javax.swing.JLabel();
        jLblTo1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSliderTreshold4 = new javax.swing.JSlider();
        jSliderTreshold5 = new javax.swing.JSlider();
        jSliderTreshold6 = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLlbFrom2 = new javax.swing.JLabel();
        jLblBy2 = new javax.swing.JLabel();
        jLblTo2 = new javax.swing.JLabel();
        jSliderTreshold7 = new javax.swing.JSlider();
        jSliderTreshold8 = new javax.swing.JSlider();
        jSliderTreshold9 = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLblFrom3 = new javax.swing.JLabel();
        jLblTo3 = new javax.swing.JLabel();
        jLblBy3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSliderTreshold1.setMaximum(255);
        jSliderTreshold1.setMinorTickSpacing(1);
        jSliderTreshold1.setPaintTicks(true);
        jSliderTreshold1.setToolTipText("");
        jSliderTreshold1.setValue(128);
        jSliderTreshold1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTreshold1MouseDragged(evt);
            }
        });

        jLabel1.setText("First treshold");

        jLabel2.setText("From");

        jLabel3.setText("To");

        jSliderTreshold2.setMaximum(255);
        jSliderTreshold2.setMinorTickSpacing(1);
        jSliderTreshold2.setPaintTicks(true);
        jSliderTreshold2.setToolTipText("");
        jSliderTreshold2.setValue(128);
        jSliderTreshold2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTreshold2MouseDragged(evt);
            }
        });

        jLabel4.setText("By");

        jSliderTreshold3.setMaximum(255);
        jSliderTreshold3.setMinorTickSpacing(1);
        jSliderTreshold3.setPaintTicks(true);
        jSliderTreshold3.setToolTipText("");
        jSliderTreshold3.setValue(128);
        jSliderTreshold3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTreshold3MouseDragged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Mutli-Treshold");

        jLabel6.setText("Second treshold");

        jLabel7.setText("Third treshold");

        jSliderTreshold4.setMaximum(255);
        jSliderTreshold4.setMinorTickSpacing(1);
        jSliderTreshold4.setPaintTicks(true);
        jSliderTreshold4.setToolTipText("");
        jSliderTreshold4.setValue(129);
        jSliderTreshold4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTreshold4MouseDragged(evt);
            }
        });

        jSliderTreshold5.setMaximum(255);
        jSliderTreshold5.setMinorTickSpacing(1);
        jSliderTreshold5.setPaintTicks(true);
        jSliderTreshold5.setToolTipText("");
        jSliderTreshold5.setValue(129);
        jSliderTreshold5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTreshold5MouseDragged(evt);
            }
        });

        jSliderTreshold6.setMaximum(255);
        jSliderTreshold6.setMinorTickSpacing(1);
        jSliderTreshold6.setPaintTicks(true);
        jSliderTreshold6.setToolTipText("");
        jSliderTreshold6.setValue(129);
        jSliderTreshold6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTreshold6MouseDragged(evt);
            }
        });

        jLabel8.setText("From");

        jLabel9.setText("To");

        jLabel10.setText("By");

        jSliderTreshold7.setMaximum(255);
        jSliderTreshold7.setMinorTickSpacing(1);
        jSliderTreshold7.setPaintTicks(true);
        jSliderTreshold7.setToolTipText("");
        jSliderTreshold7.setValue(130);
        jSliderTreshold7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTreshold7MouseDragged(evt);
            }
        });

        jSliderTreshold8.setMaximum(255);
        jSliderTreshold8.setMinorTickSpacing(1);
        jSliderTreshold8.setPaintTicks(true);
        jSliderTreshold8.setToolTipText("");
        jSliderTreshold8.setValue(130);
        jSliderTreshold8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTreshold8MouseDragged(evt);
            }
        });

        jSliderTreshold9.setMaximum(255);
        jSliderTreshold9.setMinorTickSpacing(1);
        jSliderTreshold9.setPaintTicks(true);
        jSliderTreshold9.setToolTipText("");
        jSliderTreshold9.setValue(130);
        jSliderTreshold9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSliderTreshold9MouseDragged(evt);
            }
        });

        jLabel11.setText("From");

        jLabel12.setText("To");

        jLabel13.setText("By");

        jButton1.setText("Validate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSliderTreshold4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSliderTreshold1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSliderTreshold7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLblFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jSliderTreshold2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLlbFrom2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jSliderTreshold5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLblFrom3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jSliderTreshold8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderTreshold3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblTo2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderTreshold6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLblTo3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderTreshold9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblBy1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblBy2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblBy3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSliderTreshold1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(jSliderTreshold2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLblFrom1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLblTo1))
                            .addComponent(jSliderTreshold3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblBy1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSliderTreshold4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSliderTreshold5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSliderTreshold6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLlbFrom2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLblTo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblBy2))))
                    .addComponent(jLabel8))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSliderTreshold7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jSliderTreshold8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderTreshold9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLblFrom3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLblTo3))
                    .addComponent(jLblBy3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderTreshold1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTreshold1MouseDragged
        // TODO add your handling code here:
        jLblFrom1.setText(Integer.toString(jSliderTreshold1.getValue()));
    }//GEN-LAST:event_jSliderTreshold1MouseDragged

    private void jSliderTreshold2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTreshold2MouseDragged
        // TODO add your handling code here:
        jLblTo1.setText(Integer.toString(jSliderTreshold2.getValue()));
    }//GEN-LAST:event_jSliderTreshold2MouseDragged

    private void jSliderTreshold3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTreshold3MouseDragged
        // TODO add your handling code here:
        jLblBy1.setText(Integer.toString(jSliderTreshold3.getValue()));
    }//GEN-LAST:event_jSliderTreshold3MouseDragged

    private void jSliderTreshold4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTreshold4MouseDragged
        // TODO add your handling code here:
        jLlbFrom2.setText(Integer.toString(jSliderTreshold4.getValue()));
    }//GEN-LAST:event_jSliderTreshold4MouseDragged

    private void jSliderTreshold5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTreshold5MouseDragged
        // TODO add your handling code here:
        jLblTo2.setText(Integer.toString(jSliderTreshold5.getValue()));
    }//GEN-LAST:event_jSliderTreshold5MouseDragged

    private void jSliderTreshold6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTreshold6MouseDragged
        // TODO add your handling code here:
        jLblBy2.setText(Integer.toString(jSliderTreshold6.getValue()));
    }//GEN-LAST:event_jSliderTreshold6MouseDragged

    private void jSliderTreshold7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTreshold7MouseDragged
        // TODO add your handling code here:
        jLblFrom3.setText(Integer.toString(jSliderTreshold7.getValue()));
    }//GEN-LAST:event_jSliderTreshold7MouseDragged

    private void jSliderTreshold8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTreshold8MouseDragged
        // TODO add your handling code here:
        jLblTo3.setText(Integer.toString(jSliderTreshold8.getValue()));
    }//GEN-LAST:event_jSliderTreshold8MouseDragged

    private void jSliderTreshold9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderTreshold9MouseDragged
        // TODO add your handling code here:
        jLblBy3.setText(Integer.toString(jSliderTreshold9.getValue()));
    }//GEN-LAST:event_jSliderTreshold9MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tab[0] = jSliderTreshold1.getValue();
        tab[1] = jSliderTreshold2.getValue();
        tab[2] = jSliderTreshold3.getValue();
        tab[3] = jSliderTreshold4.getValue();
        tab[4] = jSliderTreshold5.getValue();
        tab[5] = jSliderTreshold6.getValue();
        tab[6] = jSliderTreshold7.getValue();
        tab[7] = jSliderTreshold8.getValue();
        tab[8] = jSliderTreshold9.getValue();
        
        if(tab[1] < tab[0] || tab[4] < tab[3] || tab[7] < tab[6] || tab[3] <= tab[1] || tab[6] <= tab[4])
        {
            JOptionPane.showMessageDialog(this, "Invalid value");
        }
        else
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MTresholdDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MTresholdDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MTresholdDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MTresholdDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MTresholdDialog dialog = new MTresholdDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblBy1;
    private javax.swing.JLabel jLblBy2;
    private javax.swing.JLabel jLblBy3;
    private javax.swing.JLabel jLblFrom1;
    private javax.swing.JLabel jLblFrom3;
    private javax.swing.JLabel jLblTo1;
    private javax.swing.JLabel jLblTo2;
    private javax.swing.JLabel jLblTo3;
    private javax.swing.JLabel jLlbFrom2;
    private javax.swing.JSlider jSliderTreshold1;
    private javax.swing.JSlider jSliderTreshold2;
    private javax.swing.JSlider jSliderTreshold3;
    private javax.swing.JSlider jSliderTreshold4;
    private javax.swing.JSlider jSliderTreshold5;
    private javax.swing.JSlider jSliderTreshold6;
    private javax.swing.JSlider jSliderTreshold7;
    private javax.swing.JSlider jSliderTreshold8;
    private javax.swing.JSlider jSliderTreshold9;
    // End of variables declaration//GEN-END:variables
}
